# Generated by Django 5.0.6 on 2024-06-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.CharField(choices=[('vorstand', 'Vorstand'), ('advice', 'Beratung')], default='vorstand', max_length=8),
        ),
    ]
