# Generated by Django 5.0.6 on 2024-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teammember_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('news', 'News'), ('contact', 'Contact')], default='home', max_length=8)),
            ],
        ),
    ]
