# Generated by Django 5.0.6 on 2024-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autoren'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Eintrag', 'verbose_name_plural': 'Blog Einträge'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Angebot', 'verbose_name_plural': 'Angebote'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Seite', 'verbose_name_plural': 'Seiten'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Mitglied', 'verbose_name_plural': 'Team Mitglieder'},
        ),
        migrations.AddField(
            model_name='offer',
            name='frontpage',
            field=models.BooleanField(default=False),
        ),
    ]
