# Generated by Django 5.0.6 on 2024-08-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_author_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image_alt',
        ),
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('news', 'News'), ('offer', 'Angebot'), ('about', 'About'), ('membership', 'Mitgliedschaft'), ('contact', 'Contact'), ('links', 'Links'), ('agb', 'AGB'), ('impressum', 'Impressum'), ('privacy', 'Datenschutzerklärung')], default='home', max_length=10),
        ),
    ]
