# Generated by Django 5.0.6 on 2024-08-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_link_image_alt_link_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('news', 'News'), ('offer', 'Angebot'), ('about', 'About'), ('membership', 'Mitgliedschaft'), ('contact', 'Kontakt'), ('links', 'Links'), ('agb', 'AGB'), ('impressum', 'Impressum'), ('privacy', 'Datenschutzerklärung')], max_length=10, unique=True),
        ),
    ]
