# Generated by Django 5.0.6 on 2024-09-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_page_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['order'], 'verbose_name': 'Angebot', 'verbose_name_plural': 'Angebote'},
        ),
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
