# Generated by Django 5.0.6 on 2024-09-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_blogpost_img_alter_blogpost_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='img',
        ),
    ]
